# Generated by Django 4.1.2 on 2022-10-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookinfo_rateduser_alter_bookchapter_seenbyuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookchapter',
            old_name='bookChapter',
            new_name='book',
        ),
    ]
