# Generated by Django 4.1.2 on 2022-10-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_bookchapter_bookchapter_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='userRating',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bookRatings',
        ),
    ]
