# Generated by Django 4.1.2 on 2022-10-26 22:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_bookinfo_userrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bookImage',
            field=models.ImageField(default='books/nopreview.jpg', upload_to=main.models.BookInfo.upload_image_path),
        ),
    ]
